Frontend:
  impl: SimpleO3
  clock_ratio: 8
  num_expected_insts: 500000
  traces: 
    # - configs/example/example_prac_attacker.trace
    - configs/traces/example_inst.trace

  Translation:
    impl: RandomTranslation
    # 2GB
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: HB_DRAM
    org:
      preset: HB_16Mb_x64
    timing:
      preset: HB_500SDR
      # nRRDL: 1
      # nRRDS: 1

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: ClosedRowPolicy
      cap: 4
      # impl: OpenRowPolicy
    plugins:

  AddrMapper:
    impl: ChRaBaRoCo