Frontend:
  impl: LoadStoreTrace
  clock_ratio: 1
  # num_expected_insts: 500000
  path: configs/example/test.trace

  Translation:
    impl: NoTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM 
  clock_ratio: 1
  DRAM:
    impl: DDR4
    org:
      preset: DDR4_8Gb_x8
      channel: 1
      rank: 2
    timing:
      preset: DDR4_2400R

  Controller:
    impl: Generic 
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    plugins:

  AddrMapper:
    # impl: RoBaRaCoCh
    impl: ChRaBaRoCo
